add redirect for all other frontend request.
DivanteLtd/magento1-external-checkout pull request #6
Opened 2019-09-26 12:34 UTC by ngongoll

i added a redirect for all frontend calls. 
in backend config you are able to exclude paths if you need to. default is checkout/onepage and all calls for Divante_VueStorefrontExternalCheckout and Divante_VueStorefrontBridge module

2019-09-26 12:53 UTC, ResuBaka commented
So this is so you can redirect all calls that go magento to the vsf frontend home page that you didn't exclude in the config?

Am I understanding that right?

2019-09-26 12:54 UTC, ngongoll commented
yes that's right

2019-10-01 14:00 UTC, ResuBaka requested changes

2019-10-01 14:00 UTC, ResuBaka commented on app/code/community/Divante/VueStorefrontExternalCheckout/etc/config.xml
> +                <externalcheckout_url>order-success</externalcheckout_url>
I would still prefer when this is empty as it other wise would be a breaking change for stores as it was previews an empty string so you were not redirected to vsf success page.

2019-10-01 14:03 UTC, ResuBaka commented
I only found one thing, otherwise it is a great feature to have. 

I can only see that some people could break there payment provider or other modules when they use a frontend controller. But there I think they need to check it for them self it it breaks something or not.

2019-10-10 14:16 UTC, ResuBaka approved these changes

2019-10-16 17:09 UTC, merged